// The Recipe Database
window.recipes = {
    // --- BASICS ---
    "Earth+Water": { name: "Mud", icon: "💩" },
    "Fire+Water": { name: "Steam", icon: "🌫️" },
    "Earth+Fire": { name: "Lava", icon: "🌋" },
    "Earth+Wind": { name: "Dust", icon: "🤧" },
    "Fire+Wind": { name: "Smoke", icon: "🚬" },
    "Water+Wind": { name: "Wave", icon: "🌊" },
    "Water+Water": { name: "Lake", icon: "🛶" },
    "Earth+Earth": { name: "Land", icon: "⛰️" },
    "Fire+Fire": { name: "Heat", icon: "🌡️" },
    "Wind+Wind": { name: "Tornado", icon: "🌪️" },
    "Lava+Water": { name: "Stone", icon: "🪨" },
    "Stone+Wind": { name: "Sand", icon: "⏳" },
    "Fire+Sand": { name: "Glass", icon: "🥃" },
    "Fire+Stone": { name: "Metal", icon: "🤘" },
    "Mud+Fire": { name: "Brick", icon: "🧱" },
    "Steam+Wind": { name: "Cloud", icon: "☁️" },
    "Cloud+Water": { name: "Rain", icon: "🌧️" },
    "Cloud+Fire": { name: "Lightning", icon: "⚡" },
    "Cloud+Ice": { name: "Snow", icon: "❄️" },
    "Fire+Ice": { name: "Water", icon: "💧" },
    "Water+Cold": { name: "Ice", icon: "🧊" },
    "Air+Fire": { name: "Energy", icon: "🔋" },
    "Energy+Cloud": { name: "Storm", icon: "⛈️" },
    "Earth+Energy": { name: "Magnet", icon: "🧲" },

    // --- NATURE ---
    "Earth+Rain": { name: "Plant", icon: "🌱" },
    "Plant+Water": { name: "Swamp", icon: "🐊" },
    "Earth+Plant": { name: "Tree", icon: "🌲" },
    "Tree+Tree": { name: "Forest", icon: "🌳" },
    "Forest+Rain": { name: "Jungle", icon: "🌴" },
    "Plant+Sun": { name: "Flower", icon: "🌺" },
    "Flower+Sun": { name: "Sunflower", icon: "🌻" },
    "Plant+Wind": { name: "Dandelion", icon: "🌬️" },
    "Plant+Sand": { name: "Cactus", icon: "🌵" },
    "Forest+Tree": { name: "Wood", icon: "🪵" },
    "Sand+Sand": { name: "Desert", icon: "🐫" },
    "Desert+Water": { name: "Oasis", icon: "🏝️" },
    "Mountain+Water": { name: "Waterfall", icon: "🏞️" },
    "Life+Water": { name: "Fish", icon: "🐟" },
    "Life+Wind": { name: "Bird", icon: "🐦" },
    "Bird+Water": { name: "Duck", icon: "🦆" },
    "Bird+Ice": { name: "Penguin", icon: "🐧" },
    "Cat+Plant": { name: "Catnip", icon: "🌿" },
    "Fish+Electricity": { name: "Electric Eel", icon: "⚡" },
    "Horse+Black": { name: "Nightmare", icon: "🐴" },
    "Horse+Sea": { name: "Seahorse", icon: "🌊" },
    "Bear+Ice": { name: "Polar Bear", icon: "🐻‍❄️" },
    "Bear+Honey": { name: "Winnie", icon: "🧸" },
    "Cat+Dog": { name: "Catdog", icon: "🐶" },
    "Bird+Metal": { name: "Airplane", icon: "✈️" },
    "Fish+Gold": { name: "Goldfish", icon: "🐠" },
    "Lizard+Fire": { name: "Dragon", icon: "🐉" },
    "Dragon+Ice": { name: "Ice Dragon", icon: "❄️" },
    "Mouse+Cheese": { name: "Rat", icon: "🐀" },
    "Spider+Web": { name: "Spider", icon: "🕷️" },
    "Bee+Flower": { name: "Honey", icon: "🍯" },
    "Cow+Grass": { name: "Milk", icon: "🥛" },
    "Pig+Fire": { name: "Bacon", icon: "🥓" },
    "Wolf+Moon": { name: "Werewolf", icon: "🐺" },
    "Lion+Human": { name: "Sphinx", icon: "🗿" },
    "Horse+Human": { name: "Centaur", icon: "🐎" },

    // --- POP CULTURE ---
    "Human+Spider": { name: "Spiderman", icon: "🕸️" },
    "Bat+Human": { name: "Batman", icon: "🦇" },
    "Human+Iron": { name: "Ironman", icon: "🤖" },
    "Green+Human": { name: "Hulk", icon: "💪" },
    "Claw+Metal": { name: "Wolverine", icon: "🐺" },
    "God+Hammer": { name: "Thor", icon: "⚡" },
    "America+Shield": { name: "Captain America", icon: "🛡️" },
    "Cat+Woman": { name: "Catwoman", icon: "🐈‍⬛" },
    "Clown+Insane": { name: "Joker", icon: "🤡" },
    "Cape+Man": { name: "Superman", icon: "🦸" },
    "Ring+Volcano": { name: "Sauron", icon: "👁️" },
    "Ring+Hobbit": { name: "Frodo", icon: "🦶" },
    "Magic+School": { name: "Hogwarts", icon: "🏰" },
    "Boy+Lightning": { name: "Harry Potter", icon: "⚡" },
    "Star+War": { name: "Star Wars", icon: "⚔️" },
    "Father+Sky": { name: "Darth Vader", icon: "👺" },
    "Green+Goblin": { name: "Yoda", icon: "👂" },
    "Sword+Light": { name: "Lightsaber", icon: "🤺" },
    "Dinosaur+Park": { name: "Jurassic Park", icon: "🦖" },
    "Ship+Iceberg": { name: "Titanic", icon: "🚢" },
    "Ghost+Trap": { name: "Ghostbusters", icon: "🚫" },
    "Ogre+Donkey": { name: "Shrek", icon: "🤢" },
    "Toy+Story": { name: "Woody", icon: "🤠" },
    "Fish+Clown": { name: "Nemo", icon: "🐠" },
    "Princess+Ice": { name: "Elsa", icon: "❄️" },
    "Sponge+Sea": { name: "Spongebob", icon: "🧽" },
    "Mouse+Magic": { name: "Mickey", icon: "🐭" },
    "Plumber+Mushroom": { name: "Mario", icon: "🍄" },
    "Hedgehog+Speed": { name: "Sonic", icon: "🦔" },
    "Elf+Sword": { name: "Link", icon: "🗡️" },
    "Princess+Zelda": { name: "Zelda", icon: "👸" },
    "Block+Game": { name: "Minecraft", icon: "🟩" },
    "Gun+Game": { name: "Call of Duty", icon: "🔫" },
    "Imposter+Space": { name: "Among Us", icon: "ඞ" },
    "Monster+Ball": { name: "Pokemon", icon: "🔴" },
    "Mouse+Electricity": { name: "Pikachu", icon: "⚡" },

    // --- COUNTRIES ---
    "Land+Sushi": { name: "Japan", icon: "🇯🇵" },
    "Burger+Land": { name: "USA", icon: "🇺🇸" },
    "Eagle+Land": { name: "USA", icon: "🇺🇸" },
    "Land+Tea": { name: "UK", icon: "🇬🇧" },
    "Beer+Land": { name: "Germany", icon: "🇩🇪" },
    "Land+Maple": { name: "Canada", icon: "🇨🇦" },
    "Land+Pasta": { name: "Italy", icon: "🇮🇹" },
    "Land+Pizza": { name: "Italy", icon: "🇮🇹" },
    "Dragon+Land": { name: "China", icon: "🇨🇳" },
    "Land+Pyramid": { name: "Egypt", icon: "🇪🇬" },
    "Kangaroo+Land": { name: "Australia", icon: "🇦🇺" },
    "Land+Vodka": { name: "Russia", icon: "🇷🇺" },
    "Ice+Land": { name: "Iceland", icon: "🇮🇸" },
    "Land+Leprechaun": { name: "Ireland", icon: "🇮🇪" },
    "Land+Taco": { name: "Mexico", icon: "🇲🇽" },
    "Land+Wine": { name: "France", icon: "🇫🇷" },
    "City+Love": { name: "Paris", icon: "🗼" },
    "City+Fog": { name: "London", icon: "💂" },
    "City+Sin": { name: "Las Vegas", icon: "🎰" },
    "Apple+City": { name: "New York", icon: "🗽" },
    "Canal+City": { name: "Venice", icon: "🛶" },
    "Wall+China": { name: "Great Wall", icon: "🧱" },
    "Cold+Continent": { name: "Antarctica", icon: "🐧" },

    // --- FOOD ---
    "Bread+Meat": { name: "Burger", icon: "🍔" },
    "Bread+Sausage": { name: "Hot Dog", icon: "🌭" },
    "Cheese+Dough": { name: "Pizza", icon: "🍕" },
    "Dough+Sugar": { name: "Cookie", icon: "🍪" },
    "Chocolate+Dough": { name: "Brownie", icon: "🍫" },
    "Egg+Fire": { name: "Omelette", icon: "🍳" },
    "Fish+Rice": { name: "Sushi", icon: "🍣" },
    "Potato+Oil": { name: "Fries", icon: "🍟" },
    "Corn+Fire": { name: "Popcorn", icon: "🍿" },
    "Honey+Sugar": { name: "Candy", icon: "🍬" },
    "Cake+Cheese": { name: "Cheesecake", icon: "🍰" },
    "Coffee+Water": { name: "Espresso", icon: "☕" },
    "Coffee+Milk": { name: "Latte", icon: "☕" },
    "Fruit+Sugar": { name: "Jam", icon: "🍯" },
    "Milk+Ice": { name: "Ice Cream", icon: "🍦" },
    "Grape+Time": { name: "Wine", icon: "🍷" },
    "Barley+Water": { name: "Beer", icon: "🍺" },
    "Potato+Vodka": { name: "Vodka", icon: "🍸" },
    "Rice+Seaweed": { name: "Sushi", icon: "🍱" },
    "Bread+Cheese": { name: "Sandwich", icon: "🥪" },
    "Bread+Fire": { name: "Toast", icon: "🍞" },
    "Fire+Meat": { name: "Steak", icon: "🥩" },
    "Bean+Hot Water": { name: "Coffee", icon: "☕" },
    "Leaf+Hot Water": { name: "Tea", icon: "🍵" },
    "Dough+Tomato": { name: "Pizza", icon: "🍕" },
    "Fish+Fire": { name: "Cooked Fish", icon: "🍤" },
    "Chicken+Fire": { name: "Roast Chicken", icon: "🍗" },
    "Cow+Fire": { name: "Steak", icon: "🥩" },
    "Pig+Fire": { name: "Ham", icon: "🍖" },

    // --- SPACE ---
    "Cloud+Cloud": { name: "Sky", icon: "🌌" },
    "Fire+Sky": { name: "Sun", icon: "☀️" },
    "Sky+Stone": { name: "Moon", icon: "🌙" },
    "Sun+Moon": { name: "Eclipse", icon: "🌒" },
    "Rocket+Sky": { name: "Space", icon: "🌌" },
    "Space+Star": { name: "Galaxy", icon: "🌀" },
    "Galaxy+Galaxy": { name: "Universe", icon: "🤯" },
    "Space+Stone": { name: "Meteor", icon: "☄️" },
    "Meteor+Earth": { name: "Dinosaur", icon: "🦕" },
    "Human+Space": { name: "Astronaut", icon: "👨‍🚀" },
    "Alien+Rocket": { name: "UFO", icon: "🛸" },
    "Star+Time": { name: "Black Hole", icon: "🕳️" },
    "Planet+Red": { name: "Mars", icon: "🔴" },
    "Planet+Ring": { name: "Saturn", icon: "🪐" },
    "Planet+Life": { name: "Earth", icon: "🌍" },
    "Gas+Giant": { name: "Jupiter", icon: "🟠" },
    "Star+Explosion": { name: "Supernova", icon: "💥" },
    "Void+Time": { name: "Big Bang", icon: "🎇" },

    // --- TECH ---
    "Fire+Steam": { name: "Engine", icon: "🚂" },
    "Engine+Metal": { name: "Car", icon: "🚗" },
    "Car+Car": { name: "Bus", icon: "🚌" },
    "Engine+Water": { name: "Boat", icon: "🚤" },
    "Boat+Engine": { name: "Ship", icon: "🚢" },
    "Engine+Sky": { name: "Airplane", icon: "✈️" },
    "Airplane+Space": { name: "Rocket", icon: "🚀" },
    "Lightning+Metal": { name: "Electricity", icon: "⚡" },
    "Electricity+Glass": { name: "Light Bulb", icon: "💡" },
    "Light Bulb+Wire": { name: "Computer", icon: "💻" },
    "Computer+Computer": { name: "Internet", icon: "🌐" },
    "Computer+Human": { name: "Programmer", icon: "🤓" },
    "Internet+Human": { name: "Influencer", icon: "🤳" },
    "Computer+Knowledge": { name: "AI", icon: "🤖" },
    "AI+Robot": { name: "Terminator", icon: "🦾" },
    "Apple+Phone": { name: "iPhone", icon: "📱" },
    "Android+Phone": { name: "Samsung", icon: "📱" },
    "Computer+Letter": { name: "Email", icon: "📧" },
    "Game+Video": { name: "Gamer", icon: "🎮" },
    "Battery+Car": { name: "Tesla", icon: "🚗" },
    "City+Fog": { name: "Smog", icon: "🌫️" },
    "Money+Paper": { name: "Dollar", icon: "💵" },
    "Coin+Gold": { name: "Treasure", icon: "🏴‍☠️" },
    "Clock+Wall": { name: "Time", icon: "⏰" },
    "Glass+Eye": { name: "Glasses", icon: "👓" },
    "Sun+Glasses": { name: "Sunglasses", icon: "😎" },
    "Camera+Phone": { name: "Instagram", icon: "📸" },
    "Video+Time": { name: "TikTok", icon: "🎵" },
    "Cat+Video": { name: "Youtube", icon: "📺" },
    "Book+Face": { name: "Facebook", icon: "📘" },
    "Bird+Internet": { name: "Twitter", icon: "🐦" },

    // --- JOBS ---
    "Brick+Brick": { name: "Wall", icon: "🧗" },
    "Wall+Wall": { name: "House", icon: "🏠" },
    "House+House": { name: "Village", icon: "🏘️" },
    "Village+Village": { name: "Town", icon: "🏙️" },
    "Town+Town": { name: "City", icon: "🌆" },
    "Human+Book": { name: "Student", icon: "🎒" },
    "Student+Time": { name: "Graduate", icon: "🎓" },
    "Human+Fire": { name: "Fireman", icon: "👨‍🚒" },
    "Human+Tool": { name: "Engineer", icon: "👷" },
    "Human+Weapon": { name: "Soldier", icon: "🪖" },
    "Soldier+Soldier": { name: "Army", icon: "🎖️" },
    "Human+Money": { name: "Rich", icon: "🤑" },
    "Human+Law": { name: "Lawyer", icon: "⚖️" },
    "Human+Sick": { name: "Doctor", icon: "🩺" },
    "Human+Art": { name: "Artist", icon: "🎨" },
    "Human+Music": { name: "Musician", icon: "🎻" },
    "King+Woman": { name: "Queen", icon: "👑" },
    "Man+Royal": { name: "King", icon: "👑" },
    "Castle+Human": { name: "Knight", icon: "🛡️" },
    "Ship+Gun": { name: "Pirate", icon: "🏴‍☠️" },
    "Garden+Human": { name: "Gardener", icon: "👩‍🌾" },

    // --- HORROR ---
    "Corpse+Electricity": { name: "Frankenstein", icon: "🧟‍♂️" },
    "Ghost+House": { name: "Haunted House", icon: "🏚️" },
    "Blood+Human": { name: "Vampire", icon: "🧛" },
    "Human+Night": { name: "Thief", icon: "🥷" },
    "Cloth+Human": { name: "Mummy", icon: "🤕" },
    "Broom+Witch": { name: "Flying", icon: "🧹" },
    "Magic+Woman": { name: "Witch", icon: "🧙‍♀️" },
    "Death+Love": { name: "Romeo", icon: "🥀" },
    "Alien+City": { name: "Invasion", icon: "🛸" },
    "Grave+Stone": { name: "Tombstone", icon: "🪦" },
    "Death+Human": { name: "Ghost", icon: "👻" },
    "Bone+Dog": { name: "Skeleton", icon: "💀" },
    "Pumpkin+Fire": { name: "Jack-o-lantern", icon: "🎃" },
    "Devil+Human": { name: "Demon", icon: "👿" },
    "God+Human": { name: "Angel", icon: "👼" },
    "Fire+Lizard": { name: "Dragon", icon: "🐉" },
    "Dragon+Water": { name: "Sea Serpent", icon: "🐍" },
    "Bird+Horse": { name: "Pegasus", icon: "🎠" },
    "Horse+Horn": { name: "Unicorn", icon: "🦄" },
    "Fish+Woman": { name: "Mermaid", icon: "🧜‍♀️" },
    "Giant+Human": { name: "Titan", icon: "🗿" },

    // --- SCIENCE ---
    "Paper+Pencil": { name: "Art", icon: "🎨" },
    "Wood+Coal": { name: "Pencil", icon: "✏️" },
    "Paper+Wood": { name: "Book", icon: "📖" },
    "Knowledge+Paper": { name: "Book", icon: "📚" },
    "Love+Time": { name: "Marriage", icon: "💍" },
    "Blade+Wood": { name: "Sword", icon: "⚔️" },
    "Blade+Human": { name: "Warrior", icon: "🛡️" },
    "Fire+Gunpowder": { name: "Explosion", icon: "💥" },
    "Dust+Fire": { name: "Gunpowder", icon: "🧨" },
    "Explosion+Sky": { name: "Firework", icon: "🎆" },
    "Wind+Paper": { name: "Kite", icon: "🪁" },
    "Sand+Glass": { name: "Time", icon: "🕰️" },
    "Rain+Sun": { name: "Rainbow", icon: "🌈" },
    "Apple+Gravity": { name: "Newton", icon: "🔭" },
    "Earth+Gravity": { name: "Physics", icon: "⚛️" },
    "Life+Knowledge": { name: "Biology", icon: "🧬" },
    "Chemical+Science": { name: "Chemistry", icon: "🧪" },
    "Math+Numbers": { name: "Calculator", icon: "🧮" },
    "Idea+Light": { name: "Invention", icon: "💡" },
    "Sound+Time": { name: "Music", icon: "🎵" },
    "Color+Light": { name: "Prism", icon: "🌈" },

    // --- MEMES ---
    "Cat+Internet": { name: "Meme", icon: "😹" },
    "Dog+Coin": { name: "Doge", icon: "🐕" },
    "Money+Money": { name: "Gold", icon: "🪙" },
    "Rich+Ship": { name: "Yacht", icon: "🛥️" },
    "Human+Bat": { name: "Batman", icon: "🦇" },
    "Human+Party": { name: "Dancer", icon: "💃" },
    "Alcohol+Human": { name: "Drunk", icon: "🥴" },
    "Drunk+Car": { name: "Crash", icon: "💥" },
    "Crash+Hospital": { name: "Ambulance", icon: "🚑" },
    "Cloud+Sun": { name: "Day", icon: "🌤️" },
    "Moon+Sun": { name: "Eclipse", icon: "🌑" },
    "Trash+Fire": { name: "Dumpster Fire", icon: "🗑️🔥" },
    "Toilet+Water": { name: "Flush", icon: "🚽" },
    "Paper+Rock": { name: "Lose", icon: "✋" },
    "Rock+Scissors": { name: "Win", icon: "✊" },
    "Scissors+Paper": { name: "Cut", icon: "✌️" }
};